Repository Dynamic-LAB/sinsungo_android, pull requests merged in 2021-08, with the labels that each got.

#306 #305 [style] UI 수정
  app/src/main/java/com/dlab/sinsungo/data/CustomBindingAdapter.kt
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/item_rcview_diet.xml
  app/src/main/res/layout/item_rcview_shopping_list.xml
Labels: style

#310 #309 [style] merge시 잘못 수정된 UI 재수정
  app/src/main/res/layout/item_rcview_diet.xml
Labels: style

#319 추천 레시피 기능 추가
  app/src/main/java/com/dlab/sinsungo/adapters/RecipeAdapter.kt
  app/src/main/java/com/dlab/sinsungo/data/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/data/RetrofitService.kt
  app/src/main/java/com/dlab/sinsungo/data/model/RecipeData.kt
  app/src/main/java/com/dlab/sinsungo/ui/RecipeFragment.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/RecipeViewModel.kt
  app/src/main/res/layout/fragment_recipe.xml
  app/src/main/res/layout/item_rcview_recommend.xml
  app/src/main/res/values/strings.xml
Labels: suho, yoongyeong, Merge Needed, Main Issue

#322 #320 [feat] : OCR ML Kit로 구현
  app/src/main/java/com/dlab/sinsungo/ui/CameraXOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/ReceiptOCRActivity.kt
  app/src/main/res/layout/activity_receipt_ocr.xml
  app/src/main/res/layout/item_rcview_receipt_ocr.xml
Labels: feature, jaeseuk, yoongyeong, Merge Needed

#323 #321 [feat] : 바코드 스캔 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/data/BarcodeRetrofitService.kt
  app/src/main/java/com/dlab/sinsungo/data/RemoteDataSource.kt
  app/src/main/java/com/dlab/sinsungo/data/model/BarcodeProduct.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/BarcodeRepository.kt
  app/src/main/java/com/dlab/sinsungo/ui/BarcodeResultActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/BarcodeScanActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/RefrigeratorFragment.kt
  app/src/main/java/com/dlab/sinsungo/utils/BarcodeAnalyzer.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/BarcodeResultViewModel.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/BarcodeScanViewModel.kt
  app/src/main/res/drawable/btn_camera.xml
  app/src/main/res/drawable/btn_gallery.xml
  app/src/main/res/drawable/btn_receipt.xml
  app/src/main/res/layout/activity_barcode_result.xml
  app/src/main/res/layout/activity_barcode_scan.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: feature, jaeseuk, yoongyeong, Review Needed
