Repository Dynamic-LAB/sinsungo_android, pull requests merged in 2021-06, with the labels that each got.

#249 #248 [feat] : 장바구니에서 냉장고 재료 추가하기
  app/src/main/java/com/dlab/sinsungo/CustomShoppingDialog.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingListAdapter.kt
  app/src/main/res/layout/dialog_shopping_to_ref.xml
  app/src/main/res/layout/item_rcview_shopping_list.xml
Labels: Main Issue, Merge Needed, feature, jaeseuk, suho

#253 코드 리팩토링, NPE fix
  app/src/main/java/com/dlab/sinsungo/CameraXOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/CustomFragmentStateAdapter.kt
  app/src/main/java/com/dlab/sinsungo/GlobalApplication.kt
  app/src/main/java/com/dlab/sinsungo/IngredientAPI.kt
  app/src/main/java/com/dlab/sinsungo/IngredientDictModel.kt
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientModel.kt
  app/src/main/java/com/dlab/sinsungo/IngredientRepository.kt
  app/src/main/java/com/dlab/sinsungo/IngredientSelfInputDialog.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/res/drawable/btn_add.xml
  app/src/main/res/drawable/btn_back.xml
  app/src/main/res/drawable/btn_camera.xml
  app/src/main/res/drawable/btn_check.xml
  app/src/main/res/drawable/btn_circle_add.xml
  app/src/main/res/drawable/btn_circle_remove.xml
  app/src/main/res/drawable/btn_close.xml
  app/src/main/res/drawable/btn_dehaze.xml
  app/src/main/res/drawable/btn_drop_item.xml
  app/src/main/res/drawable/btn_edit.xml
  app/src/main/res/drawable/btn_expand.xml
  app/src/main/res/drawable/btn_remove_circle_red.xml
  app/src/main/res/drawable/btn_save.xml
  app/src/main/res/drawable/btn_scan.xml
  app/src/main/res/drawable/btn_sort.xml
  app/src/main/res/drawable/btn_userinfo.xml
  app/src/main/res/drawable/ic_bottom_nav_basket.xml
  app/src/main/res/drawable/ic_bottom_nav_diet.xml
  app/src/main/res/drawable/ic_bottom_nav_notification.xml
  app/src/main/res/drawable/ic_bottom_nav_recipe.xml
  app/src/main/res/drawable/ic_bottom_nav_refrigerator.xml
  app/src/main/res/drawable/ic_calender.xml
  app/src/main/res/drawable/image_empty_diet.xml
  app/src/main/res/drawable/image_empty_refrigerator.xml
  app/src/main/res/drawable/image_empty_shopping.xml
  app/src/main/res/drawable/img_tutorial1.xml
  app/src/main/res/drawable/img_tutorial2.xml
  app/src/main/res/drawable/img_tutorial3.xml
  app/src/main/res/drawable/img_welcome.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_receipt_ocr.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/dialog_ingredient_self_input.xml
  app/src/main/res/layout/dialog_invite.xml
  app/src/main/res/layout/dialog_receipt_add_ingredient.xml
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/layout/fragment_tutorial.xml
  app/src/main/res/layout/item_rcview_ingredient.xml
  app/src/main/res/layout/item_rcview_receipt_ocr.xml
Labels: Merge Needed, fix, jaeseuk, refactor, yoongyeong

#255 #254 [fix] : 영수증 인식 수정
  app/src/main/java/com/dlab/sinsungo/ReceiptOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptOCRViewModel.kt
Labels: Simple, fix

#261 #257 [feat] : 냉장고 id 하드코딩 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptOCRViewModel.kt
Labels: Merge Needed, Simple, feature

#262 #258 [feat] : 기기 push token 업데이트
  app/src/main/java/com/dlab/sinsungo/ui/LoginActivity.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/LoginViewModel.kt
Labels: Merge Needed, Simple, feature

#266 #259 [feature] : 영수증 인식 텅 이미지 추가
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/res/drawable/image_empty_refrigerator.xml
  app/src/main/res/drawable/img_empty_ocr_result.xml
  app/src/main/res/drawable/img_empty_receipt.xml
  app/src/main/res/drawable/img_empty_refrigerator.xml
  app/src/main/res/layout/activity_receipt_ocr.xml
  app/src/main/res/layout/fragment_ingredient.xml
Labels: Merge Needed, Simple, feature

#269 영수증 인식 리스트 어댑터 수정, 애니메이션 추가
  app/src/main/java/com/dlab/sinsungo/ReceiptListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptOCRViewModel.kt
  app/src/main/res/layout/activity_receipt_ocr.xml
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/layout/item_rcview_receipt_ocr.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed, Simple, feature

#264 #263 [feat] : 식단 냉장고 재료 리스트
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/CustomBottomSheetDiet.kt
  app/src/main/java/com/dlab/sinsungo/DietFragment.kt
  app/src/main/java/com/dlab/sinsungo/DietIngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/DietListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/DietViewModel.kt
  app/src/main/res/layout/dialog_diet.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed, fix, jaeseuk, suho

#270 #268 [feat] : 식단 재료 리스트 null 처리
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/CustomBottomSheetDiet.kt
  app/src/main/java/com/dlab/sinsungo/DietListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/data/model/Diet.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/DietViewModel.kt
  app/src/main/res/drawable/image_empty_diet.xml
  app/src/main/res/drawable/img_no_search_data.xml
  app/src/main/res/layout/dialog_diet.xml
  app/src/main/res/layout/fragment_diet.xml
  app/src/main/res/layout/item_rcview_diet.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed, feature, jaeseuk, suho

#273 #271 장바구니 기능 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/ShoppingViewModel.kt
  app/src/main/res/drawable/image_empty_shopping.xml
  app/src/main/res/layout/fragment_shopping.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#274 알림 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/MyFirebaseMessagingService.kt
  app/src/main/java/com/dlab/sinsungo/NotificationListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/data/RetrofitService.kt
  app/src/main/java/com/dlab/sinsungo/data/model/NotificationModel.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/NotificationRepository.kt
  app/src/main/java/com/dlab/sinsungo/ui/NotificationFragment.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/NotificationViewModel.kt
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_rcview_notification.xml
  app/src/main/res/values/strings.xml
Labels: Review Needed, feature, jaeseuk, yoongyeong

#276 #275 [feat] 식단 추가 수정 삭제시 아이템 상태 원상복귀
  app/src/main/java/com/dlab/sinsungo/DietFragment.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/SwipeHelperCallback.kt
  app/src/main/res/layout/fragment_diet.xml
Labels: fix

#279 #278 [feat] 냉장고 ID 받아오기
  app/src/main/java/com/dlab/sinsungo/CustomBottomSheetDiet.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/DietViewModel.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/ShoppingViewModel.kt
Labels: fix

#280 코드 정리, 알림 텅 이미지
  app/src/main/java/com/dlab/sinsungo/CustomConfirmDialog.kt
  app/src/main/java/com/dlab/sinsungo/DietListDialog.kt
  app/src/main/java/com/dlab/sinsungo/MemberAdapter.kt
  app/src/main/java/com/dlab/sinsungo/NoticeAdapter.kt
  app/src/main/java/com/dlab/sinsungo/data/RetrofitService.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/RecipeRepository.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/RefrigeratorRepository.kt
  app/src/main/java/com/dlab/sinsungo/ui/ContactActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/HelpActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/LawActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/LoginActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/MyPageActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/NoticeActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/NoticeDetailActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/RecipeDetailActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/RecipeFragment.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/TutorialViewModel.kt
  app/src/main/res/drawable/img_empty_notification.xml
  app/src/main/res/layout/activity_contact.xml
  app/src/main/res/layout/activity_help.xml
  app/src/main/res/layout/activity_law.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_notice_detail.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/layout/dialog_diet_list.xml
  app/src/main/res/layout/dialog_invite.xml
  app/src/main/res/layout/dialog_recipe_to_diet.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_recipe.xml
  app/src/main/res/layout/item_pb_loading.xml
  app/src/main/res/layout/item_rcview_member.xml
  app/src/main/res/layout/item_rcview_notice.xml
  app/src/main/res/layout/item_rcview_recipe.xml
  app/src/main/res/layout/item_rcview_user.xml
  app/src/main/res/layout/layout_title_with_back_btn.xml
  app/src/main/res/values/strings.xml
Labels: refactor, style

#295 #294 장바구니 기능 이슈 대응
  app/src/main/java/com/dlab/sinsungo/ui/ShoppingFragment.kt
  app/src/main/res/layout/dialog_shopping_to_ref.xml
  app/src/main/res/values/strings.xml
Labels: Main Issue, Review Needed, feature, fix, jaeseuk, suho

#291 #290 [feat] 식단 기능 이슈 대응
  app/src/main/java/com/dlab/sinsungo/data/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ui/dialogs/DietBottomSheet.kt
Labels: Main Issue, Review Needed, feature, fix, jaeseuk, suho

#299 #285 [fix] : 식단 검색 후 재료 사용 체크 시 재료 복사되는 에러 수정
  app/src/main/java/com/dlab/sinsungo/adapters/DietIngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ui/dialogs/DietBottomSheet.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/DietViewModel.kt
Labels: Merge Needed, fix, yoongyeong

#298 #281 [feat] : 알림 숫자 Span
  app/src/main/java/com/dlab/sinsungo/data/CustomBindingAdapter.kt
  app/src/main/res/layout/item_rcview_notification.xml
Labels: Merge Needed, feature, jaeseuk, yoongyeong

#297 냉장고/재료 기능 이슈 대응
  app/src/main/java/com/dlab/sinsungo/adapters/IngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/data/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/data/model/IngredientModel.kt
  app/src/main/java/com/dlab/sinsungo/ui/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/ui/ReceiptOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/dialogs/IngredientSelfInputDialog.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/ReceiptOCRViewModel.kt
  app/src/main/res/layout/activity_camera_ocr.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_receipt_ocr.xml
  app/src/main/res/layout/dialog_ingredient_self_input.xml
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/layout/item_rcview_ingredient.xml
  app/src/main/res/layout/item_rcview_receipt_ocr.xml
Labels: Merge Needed, feature, jaeseuk, style, yoongyeong
