Repository Dynamic-LAB/sinsungo_android, pull requests merged in 2021-04, with the labels that each got.

#45 #19 LoginActivity VIew 제작 완료
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/Event.kt
  app/src/main/res/drawable/btn_login_google.xml
  app/src/main/res/drawable/btn_login_kakao.xml
  app/src/main/res/drawable/btn_login_naver.xml
  app/src/main/res/drawable/img_login_logo.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: Merge Needed, chore, feature, style

#43 #30 냉장고 기능 view 개발 완료
  app/build.gradle
  app/src/main/java/com/dlab/sinsungo/CustomFragmentStateAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/res/drawable/btn_add.xml
  app/src/main/res/drawable/btn_camera.xml
  app/src/main/res/drawable/btn_close.xml
  app/src/main/res/drawable/btn_edit.xml
  app/src/main/res/drawable/btn_scan.xml
  app/src/main/res/drawable/btn_sort.xml
  app/src/main/res/drawable/btn_userinfo.xml
  app/src/main/res/drawable/image_empty_refrigerator.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/layout/fragment_refrigerator.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed, feature, style

#47 #44 [style] : string 리팩토링
  app/src/main/res/values/strings.xml
Labels: style

#54 #53 [style] : theme night 삭제, theme내 오타 수정
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: fix, style

#56 #46 [style] : 냉장고 View Text Style 적용
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/layout/fragment_refrigerator.xml
Labels: Merge Needed, style, yoongyeong

#57 #55 [style] : 냉장고 View Style 수정
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/layout/fragment_refrigerator.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Merge Needed, style

#66 #58 [style] : 냉장고 리사이클러뷰 항목 item View 개발
  app/src/main/res/layout/item_rcview_ingredient.xml
Labels: Merge Needed, style

#73 #49 [feature] : LoginRepository 패턴 구현
  app/src/main/java/com/dlab/sinsungo/data/model/User.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/login/LoginRemoteDataSource.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/login/LoginRepository.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/login/LoginService.kt
Labels: Merge Needed, feature, suho, yoongyeong

#74 #20 [feature] : Login 기능 구현중
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/GlobalApplication.kt
  app/src/main/java/com/dlab/sinsungo/ui/LoginActivity.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/LoginViewModel.kt
  app/src/main/res/values/strings.xml
Labels: Merge Needed, chore, feature, suho, yoongyeong

#76 #61 냉장고 커스텀 다이얼로그 개발
  .idea/render.experimental.xml
  app/src/main/java/com/dlab/sinsungo/RefrigeratorCustomDialog.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/res/drawable/border_bottom.xml
  app/src/main/res/drawable/btn_expand.xml
  app/src/main/res/drawable/ic_calender.xml
  app/src/main/res/drawable/ic_cutlery.xml
  app/src/main/res/drawable/shape_dialog.xml
  app/src/main/res/drawable/shape_inner_dialog.xml
  app/src/main/res/layout/dialog_refrigerator.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/menu/menu_count_type.xml
  app/src/main/res/menu/menu_exdate_type.xml
  app/src/main/res/menu/menu_ref_categories.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Main Issue, Merge Needed, feature, jaeseuk, style, yoongyeong

#99 #86 재료 가져오기 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/BaseService.kt
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientApi.kt
  app/src/main/java/com/dlab/sinsungo/IngredientDiffCallback.kt
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientModel.kt
  app/src/main/java/com/dlab/sinsungo/IngredientRepository.kt
  app/src/main/java/com/dlab/sinsungo/IngredientService.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModelFactory.kt
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/layout/item_rcview_ingredient.xml
  app/src/main/res/values/strings.xml
Labels: Main Issue, Merge Needed, jaeseuk, yoongyeong

#111 #67 [feat] : Fragment Title 레이아웃 MainActivity로 이동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_refrigerator.xml
Labels: Merge Needed, feature, style, yoongyeong

#113 #84 [feat] : getColor 마시멜로 이상 대응 수정
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/layout/item_rcview_ingredient.xml
Labels: Merge Needed, Simple, feature

#110 #104 [Fix] : 장바구니 다이얼로그 에러
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
Labels: Merge Needed, fix

#114 #107 [feat] : 재료 입력 다이얼로그 TextWatcher 수정
  app/src/main/java/com/dlab/sinsungo/RefrigeratorCustomDialog.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/res/layout/dialog_refrigerator.xml
Labels: Merge Needed, Simple, feature
