Repository Dynamic-LAB/sinsungo_android, pull requests merged in 2021-05, with the labels that each got.

#122 #112 [Style] : 프래그먼트 상단 레이아웃 변경 적용
  app/src/main/res/layout/fragment_diet.xml
  app/src/main/res/layout/fragment_shopping.xml
Labels: Merge Needed, Simple, style

#118 #78 레시피 기능 개발, #103 레시피 View 개발
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/RecipeAdapter.kt
  app/src/main/java/com/dlab/sinsungo/data/RemoteDataSource.kt
  app/src/main/java/com/dlab/sinsungo/data/RetrofitService.kt
  app/src/main/java/com/dlab/sinsungo/data/model/Recipe.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/LoginRepository.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/RecipeRepository.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/login/LoginService.kt
  app/src/main/java/com/dlab/sinsungo/ui/RecipeDetailActivity.kt
  app/src/main/java/com/dlab/sinsungo/ui/RecipeFragment.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/LoginViewModel.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/RecipeDetailViewModel.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/RecipeViewModel.kt
  app/src/main/res/drawable/btn_back.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/activity_recipe_detail.xml
  app/src/main/res/layout/fragment_recipe.xml
  app/src/main/res/layout/item_pb_loading.xml
  app/src/main/res/layout/item_rcview_recipe.xml
  app/src/main/res/values/themes.xml
Labels: Main Issue, Merge Needed, feature, style, suho, yoongyeong

#123 #105 [feat] : 재료 유통기한 남은날짜 로직 구현
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientModel.kt
  app/src/main/res/drawable/bg_progress_bad.xml
  app/src/main/res/drawable/bg_progress_good.xml
  app/src/main/res/layout/item_rcview_ingredient.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed, feature, jaeseuk, yoongyeong

#126 #63 [feat] : 냉장고 커스텀 다이얼로그 클래스 생성
  app/src/main/java/com/dlab/sinsungo/RefrigeratorCustomDialog.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
Labels: Merge Needed, Simple, feature

#127 #106 [feat] : 냉장고 카테고리 탭 별로 재료 아이템 가져오기
  app/src/main/java/com/dlab/sinsungo/CustomFragmentStateAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
Labels: Merge Needed, feature, jaeseuk, yoongyeong

#129 #128 [style] : 뒤로가기 버튼 있는 상단 바 템플릿화
  app/src/main/java/com/dlab/sinsungo/ui/RecipeDetailActivity.kt
  app/src/main/res/layout/activity_recipe_detail.xml
  app/src/main/res/layout/layout_title_with_back_btn.xml
Labels: Merge Needed, refactor, style, suho, yoongyeong

#135 #109 [feat] : 재료 리사이클러뷰 정렬 구현
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/menu/menu_ingredient_sortby.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed, feature, jaeseuk, yoongyeong

#134 #133 식단 추가 기능 개발
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/data/model/Shopping.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/shopping/ShoppingRemoteDataSource.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/shopping/ShoppingRepository.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/shopping/ShoppingService.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/ShoppingViewModel.kt
  app/src/main/res/layout/dialog_shopping.xml
Labels: Main Issue, feature, jaeseuk, suho

#161 재료 직접입력 추가하기 기능 구현
  app/src/main/java/com/dlab/sinsungo/CustomFragmentStateAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientAPI.kt
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientModel.kt
  app/src/main/java/com/dlab/sinsungo/IngredientRepository.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorCustomDialog.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/res/layout/fragment_ingredient.xml
  app/src/main/res/layout/item_rcview_ingredient.xml
Labels: Main Issue, Merge Needed, feature, jaeseuk, yoongyeong

#163 #162 장바구니 목록 삭제하기 기능
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ItemDecoration.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/SwipeHelperCallback.kt
  app/src/main/java/com/dlab/sinsungo/data/RetrofitService.kt
  app/src/main/java/com/dlab/sinsungo/data/model/Shopping.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/ShoppingViewModel.kt
  app/src/main/res/drawable/btn_trash.xml
  app/src/main/res/layout/fragment_shopping.xml
  app/src/main/res/layout/item_rcview_shopping_list.xml
Labels: Merge Needed, feature, jaeseuk, suho

#173 #172 장바구니 기능 수정 기능 개발
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/ShoppingViewModel.kt
  app/src/main/res/layout/item_rcview_shopping_list.xml
Labels: Main Issue, Merge Needed, feature, jaeseuk, suho

#175 재료 삭제 기능 구현
  app/src/main/java/com/dlab/sinsungo/IngredientAPI.kt
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientRepository.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
Labels: Merge Needed, feature, jaeseuk, yoongyeong

#177 #176 [feat] : 재료 추가 직후 다이얼로그 안뜨는 이슈
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorCustomDialog.kt
Labels: Merge Needed, feature, fix, jaeseuk, yoongyeong

#179 #178 장바구니 목록 공유하기 기능
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingListAdapter.kt
  app/src/main/res/xml/filepaths.xml
Labels: Review Needed, feature, jaeseuk, suho

#181 #180 [feat] : 재료 추가하기 양방향 데이터 바인딩 사용
  app/src/main/java/com/dlab/sinsungo/Converter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientModel.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorCustomDialog.kt
  app/src/main/res/layout/dialog_refrigerator.xml
Labels: Review Needed, feature, jaeseuk, yoongyeong

#189 재료 수정하기 기능 구현
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientAPI.kt
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientRepository.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorSelfInputIngredientDialog.kt
  app/src/main/res/layout/dialog_self_input_ingredient.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed, feature, jaeseuk, yoongyeong

#193 재료 직접입력 예외처리
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
Labels: Merge Needed, jaeseuk, refactor, yoongyeong

#191 #136 [style] : 레시피, 레시피 디테일 레이아웃 수정
  app/src/main/res/layout/activity_recipe_detail.xml
  app/src/main/res/layout/fragment_recipe.xml
Labels: Apply Review, style, suho, yoongyeong

#205 #204 [feat] : 재료 ViewModel 액티비티로 이동
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorSelfInputIngredientDialog.kt
Labels: Merge Needed, feature, jaeseuk, yoongyeong

#207 영수증 인식 기능 view 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/CameraXOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/IngredientFragment.kt
  app/src/main/java/com/dlab/sinsungo/IngredientSelfInputDialog.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/res/drawable/btn_check.xml
  app/src/main/res/layout/activity_camera_ocr.xml
  app/src/main/res/layout/activity_receipt_ocr.xml
  app/src/main/res/layout/dialog_ingredient_self_input.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed, chore, feature, jaeseuk, style, yoongyeong

#227 #226 [feat] : 영수증 인식 재료 추가 기능 구현
  app/build.gradle
  app/src/main/java/com/dlab/sinsungo/CameraXOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientAPI.kt
  app/src/main/java/com/dlab/sinsungo/IngredientDictModel.kt
  app/src/main/java/com/dlab/sinsungo/IngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/IngredientModel.kt
  app/src/main/java/com/dlab/sinsungo/IngredientRepository.kt
  app/src/main/java/com/dlab/sinsungo/IngredientSelfInputDialog.kt
  app/src/main/java/com/dlab/sinsungo/IngredientViewModel.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptOCRActivity.kt
  app/src/main/java/com/dlab/sinsungo/ReceiptOCRViewModel.kt
  app/src/main/java/com/dlab/sinsungo/RefrigeratorFragment.kt
  app/src/main/res/drawable/btn_drop_item.xml
  app/src/main/res/layout/activity_receipt_ocr.xml
  app/src/main/res/layout/dialog_ingredient_self_input.xml
  app/src/main/res/layout/dialog_receipt_add_ingredient.xml
  app/src/main/res/layout/item_rcview_receipt_ocr.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Main Issue, Merge Needed, feature, jaeseuk, style, yoongyeong

#218 #125 마이페이지 뷰 개발
  app/src/main/java/com/dlab/sinsungo/CustomConfirmDialog.kt
  app/src/main/java/com/dlab/sinsungo/ui/MyPageActivity.kt
  app/src/main/res/drawable/btn_remove_circle_red.xml
  app/src/main/res/drawable/ic_master_circle.xml
  app/src/main/res/drawable/img_member.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/layout/item_rcview_member.xml
  app/src/main/res/layout/item_rcview_user.xml
Labels: Main Issue, Review Needed, feature, style, suho, yoongyeong

#230 튜토리얼 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/SplashActivity.kt
  app/src/main/java/com/dlab/sinsungo/TutorialActivity.kt
  app/src/main/java/com/dlab/sinsungo/TutorialFragment.kt
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/fragment_tutorial.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Merge Needed, feature, jaeseuk, style, yoongyeong

#231 #124 마이페이지 기능 개발
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/MemberAdapter.kt
  app/src/main/java/com/dlab/sinsungo/data/RetrofitService.kt
  app/src/main/java/com/dlab/sinsungo/data/model/Refrigerator.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/RefrigeratorRepository.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/UserRepository.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: Main Issue, Merge Needed, feature, style, suho, yoongyeong

#235 #234 [feat] : FCM 테스트 메시지 발송, 알림 테스트
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/MyFirebaseMessagingService.kt
Labels: In Develop, feature, jaeseuk, yoongyeong

#237 #236 [feat] : 튜토리얼 내용 추가
  app/src/main/java/com/dlab/sinsungo/SplashActivity.kt
  app/src/main/java/com/dlab/sinsungo/TutorialActivity.kt
  app/src/main/java/com/dlab/sinsungo/TutorialFragment.kt
  app/src/main/res/drawable/img_tutorial1.xml
  app/src/main/res/drawable/img_tutorial2.xml
  app/src/main/res/drawable/img_tutorial3.xml
  app/src/main/res/drawable/img_welcome.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/fragment_tutorial.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Merge Needed, feature, jaeseuk, yoongyeong

#240 #239 식단 기능 개발
  app/build.gradle
  app/src/main/java/com/dlab/sinsungo/CustomBindingAdapter.kt
  app/src/main/java/com/dlab/sinsungo/CustomBottomSheetDiet.kt
  app/src/main/java/com/dlab/sinsungo/DietFragment.kt
  app/src/main/java/com/dlab/sinsungo/DietIngredientListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/DietListAdapter.kt
  app/src/main/java/com/dlab/sinsungo/ShoppingFragment.kt
  app/src/main/java/com/dlab/sinsungo/SwipeHelperCallback.kt
  app/src/main/java/com/dlab/sinsungo/data/RetrofitService.kt
  app/src/main/java/com/dlab/sinsungo/data/model/Diet.kt
  app/src/main/java/com/dlab/sinsungo/data/repository/DietRepository.kt
  app/src/main/java/com/dlab/sinsungo/viewmodel/DietViewModel.kt
  app/src/main/res/drawable/btn_blank_circle.xml
  app/src/main/res/drawable/btn_circle.xml
  app/src/main/res/drawable/select_diet_ingredient.xml
  app/src/main/res/layout/activity_recipe_detail.xml
  app/src/main/res/layout/dialog_diet.xml
  app/src/main/res/layout/dialog_ingredient_self_input.xml
  app/src/main/res/layout/dialog_shopping.xml
  app/src/main/res/layout/fragment_diet.xml
  app/src/main/res/layout/item_rcview_diet.xml
  app/src/main/res/layout/item_rcview_diet_ingredient.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Main Issue, Review Needed, feature, jaeseuk, suho

#247 #246 [feat] : 튜토리얼 초대코드 입력 다이얼로그 뷰 구현
  app/src/main/java/com/dlab/sinsungo/TutorialActivity.kt
  app/src/main/res/layout/dialog_invite.xml
  app/src/main/res/values/strings.xml
Labels: Merge Needed, feature, jaeseuk
