Repository Dynamic-LAB/sinsungo_android, pull requests merged in 2021-03, with the labels that each got.

#2 #1 [chore] : ktlint 적용
  .editorconfig
  .idea/.name
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Simple, chore, suho

#11 #10 [feature] : GlobalApplication 추가
  app/src/main/java/com/dlab/sinsungo/GlobalApplication.kt
Labels: Simple, feature, jaeseuk

#13 #9 [style] : 카카오 네이티브 앱 키 추가
  app/src/main/res/values/strings.xml
Labels: Simple, jaeseuk, style

#14 #8 [chore] : 카카오 로그인 API 연동
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
Labels: Simple, chore, jaeseuk

#15 #5 [style] : 앱 아이콘 생성
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: style

#21 #6 [style] : MainActivity layout 작성
  app/src/main/res/drawable/ic_bottom_nav_basket.xml
  app/src/main/res/drawable/ic_bottom_nav_diet.xml
  app/src/main/res/drawable/ic_bottom_nav_notification.xml
  app/src/main/res/drawable/ic_bottom_nav_recipe.xml
  app/src/main/res/drawable/ic_bottom_nav_refrigerator.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/strings.xml
Labels: Review Needed, style, yoongyeong

#22 #18 [feature] : MainActivity 초기화
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/GlobalApplication.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: Merge Needed, feature

#23 #17 [feature] : SharedPreference 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/GlobalApplication.kt
  app/src/main/java/com/dlab/sinsungo/MySharedPreference.kt
Labels: Merge Needed, chore, feature

#25 #24 [style] : MainActivity 레이아웃 수정
  app/src/main/res/layout/activity_main.xml
Labels: Merge Needed, feature

#27 create pull request from Feature/main
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dlab/sinsungo/GlobalApplication.kt
  app/src/main/java/com/dlab/sinsungo/MainActivity.kt
  app/src/main/java/com/dlab/sinsungo/MySharedPreference.kt
  app/src/main/res/drawable/ic_bottom_nav_basket.xml
  app/src/main/res/drawable/ic_bottom_nav_diet.xml
  app/src/main/res/drawable/ic_bottom_nav_notification.xml
  app/src/main/res/drawable/ic_bottom_nav_recipe.xml
  app/src/main/res/drawable/ic_bottom_nav_refrigerator.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/strings.xml
Labels: feature

#36 #35, #37, #38 [style] : 스타일 수정
  app/src/main/res/font/app_font.xml
  app/src/main/res/font/nanumsquare_acb.ttf
  app/src/main/res/font/nanumsquare_acr.ttf
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/themes.xml
Labels: style

#40 #39 [fix] : font error fix
  app/src/main/res/font/app_font.xml
Labels: fix, style
